export const routes = {
    DEFAULT: "/",
    LOGIN:"/auth/login",
    FORGOT_PASSWORD:"/auth/forgot-password",
    REGISTER:'/auth/register',
    RESET_PASSWORD:'/auth/reset-password',
    DASHBOARD:"/admin/dashboard",
    AGENCY:"/admin/agencies",
    AGENCY_EDIT:"/admin/agencies/edit",
    AGENCY_ADD:"/admin/agencies/add",
    ADMIN_OFFENDER:"/admin/offender",
    ADMIN_OFFENDER_ADD:"/admin/offender/add",
    ADMIN_USERS_VIEW:"/admin/users/view",
    ADMIN_USERS_EDIT:"/admin/users/edit",
    ADD_CASE_REPORT:"/admin/users/add-case-report",
    CASE_REPORT:"/admin/users/case-report",
    VIEW_CASE_REPORT: "/admin/users/view-case-report",
    EDIT_CASE_REPORT: "/admin/users/edit-case-report",
    ERROR:"*"
};